apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kk5x2w7e7-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kk5x2w7e7-python 
  name: kk5x2w7e7-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kk5x2w7e7-python 
